management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

server:
  port: ${PORT:8080}

spring:
  application:
    name: store

  jwt:
    secret: ${JWT_SECRET}

    # The expiration period for an Access Token should be short-lived
    # 900s = 15m (Access tokens will be valid for 15 mins for this application)
    accessTokenExpiration: 900

    # The expiration period for a Refresh Token should be long-lived
    # 604800s = 7d (Refresh tokens will be valid for 7 days for this application)
    refreshTokenExpiration: 604800 # 7 Days

  profiles:
    active: dev

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}