spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Murphy1015!
  jpa:
    show-sql: true

# This is the URL for the front end application
websiteUrl: http://localhost:1234